### ISSUE TITLE
[Interview] Личные эндпоинты студента

### ISSUE THREAD

**Issue by furlupe** [ProcessesHITS1/HitsInternsBackend#25]
Сейчас нет возможности получить информацию о сезоне, в котором участвую студент (год? все равно не удобно).
Также, нет (как мне показалось) ендпоинта на получение реквестов конкретного студента (и текущего в т.ч.).

Предлагаемые эндпоинты:
GET: api/seasons/my - получение сезона, в котором находится залогиненный юзер ака студент
GET: api/requests/{studenId} - реквесты конкретного студента
~GET: api/requests/my - реквесты залогиненного студента~

**Comment by ssslakter** [comment]
@Ek128N реквесты на тебе :) (ну и)

**Comment by ssslakter** [comment]
#32
